SELECT TITLE, B.BOARD_ID, REPLY_ID, R.WRITER_ID, R.CONTENTS, TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_REPLY R ON B.BOARD_ID = R.BOARD_ID
WHERE EXTRACT(YEAR FROM B.CREATED_DATE) = 2022 AND EXTRACT(MONTH FROM B.CREATED_DATE) = 10
ORDER BY R.CREATED_DATE, B.TITLE;